##DECISION MAKING  COnditional Statement STATE MENT ~ HERE IS THE SAMPLE DATA WORKING FOR IF CONDITION
library(readr)
DISB <- read_csv("C:/Users/Arohan/Downloads/CUST_DATA.xlsb")

MAIN=sqldf('SELECT BRNCH_CDE,BRNCH_NME,ZONE_NME,REGION,COUNT(DISTINCT ACCT_NBR) AS TOT_ACCT,COUNT(DISTINCT CUST_NBR) AS TOT_CUST,SUM(LGR_BAL) AS TOT_POS,COUNT(DISTINCT CNTR_ID) AS TOT_CNTR,
              COUNT(distinct(CASE WHEN DAYSDELQ>0 THEN CNTR_ID ELSE NULL END)) AS TOT_OD_CNTR,
              COUNT(distinct(CASE WHEN DAYSDELQ <=0 THEN ACCT_NBR ELSE NULL END)) AS REG_ACCT,
              SUM(CASE WHEN DAYSDELQ <=0 THEN LGR_BAL ELSE 0 END) AS REG_AMT,
              COUNT(distinct(CASE WHEN DAYSDELQ >0 THEN ACCT_NBR ELSE NULL END)) AS OD_ACCT,
              SUM(CASE WHEN DAYSDELQ >0 THEN LGR_BAL ELSE 0 END) AS OD_AMT,
              COUNT(distinct(CASE WHEN DAYSDELQ>0 THEN ACCT_NBR ELSE NULL END)) AS PAR_0_ACCT,
              SUM(CASE WHEN DAYSDELQ>0 THEN LGR_BAL ELSE 0 END) AS PAR_0_POS,
              COUNT(distinct(CASE WHEN DAYSDELQ>30 THEN ACCT_NBR ELSE NULL END)) AS PAR_30_ACCT,
              sum(CASE WHEN DAYSDELQ>30 THEN LGR_BAL ELSE 0 END) AS PAR_30,
              COUNT(distinct(CASE WHEN DAYSDELQ>60 THEN ACCT_NBR ELSE NULL END)) AS PAR_60_ACCT,
              sum(CASE WHEN DAYSDELQ>60 THEN LGR_BAL ELSE 0 END) AS PAR_60,
              COUNT(distinct(CASE WHEN DAYSDELQ>90 THEN ACCT_NBR ELSE NULL END)) AS PAR_90_ACCT,
              sum(CASE WHEN DAYSDELQ>90 THEN LGR_BAL ELSE 0 END) AS PAR_90,
              COUNT(distinct(CASE WHEN DAYSDELQ>180 THEN ACCT_NBR ELSE NULL END)) AS PAR_180_ACCT,
              sum(CASE WHEN DAYSDELQ>180 THEN LGR_BAL ELSE 0 END) AS PAR_180 
              FROM DISB GROUP BY BRNCH_CDE,BRNCH_NME,ZONE_NME,REGION')


write.csv(MAIN,"SUMMARY.csv")
########################## 2nd Method tagging BY IF Function  & Pivot the data #############
library(readr)
DISB <- read_csv("C:/Users/Arohan/Downloads/PAR_CLIENT.xlsb")


library(dplyr)
DISB$STATEMENT= ifelse(DISB$DAYSDELQ %in% c("0":"30"),"PAR_30",
                       ifelse(DISB$DAYSDELQ %in% c("31":"60"),"PAR_60",
                              ifelse(DISB$DAYSDELQ  %in% c("61":"90"),"PAR_90","PAR_180")))


#PIVOT THE DATA

PAR_30<-filter(DISB,STATEMENT %in% c("PAR_30"))
PAR_60<-filter(DISB,STATEMENT %in% c("PAR_60"))
PAR_90<-filter(DISB,STATEMENT %in% c("PAR_90"))
PAR_180<-filter(DISB,STATEMENT %in% c("PAR_180"))

PAR30=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_30_ACCT,SUM(LGR_BAL) AS PAR_30_OUTSTANDING FROM PAR_30 GROUP BY ZONE_NME')
PAR60=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_60_ACCT,SUM(LGR_BAL) AS PAR_60_OUTSTANDING  FROM PAR_60 GROUP BY ZONE_NME')
PAR90=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_90_ACCT,SUM(LGR_BAL) AS PAR_90_OUTSTANDING  FROM PAR_90 GROUP BY ZONE_NME')
PAR180=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_180_ACCT,SUM(LGR_BAL) AS PAR_180_OUTSTANDING  FROM PAR_180 GROUP BY ZONE_NME')


ZONE=sqldf('SELECT ZONE_NME FROM DISB  GROUP BY ZONE_NME')

A=merge(ZONE,PAR30,by="ZONE_NME",all.x = TRUE)
B=merge(A,PAR60,by="ZONE_NME",all.x = TRUE)
C=merge(B,PAR90,by="ZONE_NME",all.x = TRUE)
D=merge(C,PAR180,by="ZONE_NME",all.x = TRUE)

write.csv(D,"PAR_SUMMARY.CSV")






