##DECISION MAKING STATE MENT ~ HERE IS THE SAMPLE DATA WORKING FOR IF CONDITION
library(readr)
DISB <- read_csv("C:/Users/Arohan/Downloads/PAR_CLIENT.xlsb")

library(dplyr)
DISB$STATEMENT= ifelse(DISB$DAYSDELQ %in% c("0":"30"),"PAR_30",
                       ifelse(DISB$DAYSDELQ %in% c("31":"60"),"PAR_60",
                              ifelse(DISB$DAYSDELQ  %in% c("61":"90"),"PAR_90","PAR_180")))

#PIVOT THE DATA

PAR_30<-filter(DISB,STATEMENT %in% c("PAR_30"))
PAR_60<-filter(DISB,STATEMENT %in% c("PAR_60"))
PAR_90<-filter(DISB,STATEMENT %in% c("PAR_90"))
PAR_180<-filter(DISB,STATEMENT %in% c("PAR_180"))

PAR30=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_30_ACCT,SUM(LGR_BAL) AS PAR_30_OUTSTANDING FROM PAR_30 GROUP BY ZONE_NME')
PAR60=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_60_ACCT,SUM(LGR_BAL) AS PAR_60_OUTSTANDING  FROM PAR_60 GROUP BY ZONE_NME')
PAR90=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_90_ACCT,SUM(LGR_BAL) AS PAR_90_OUTSTANDING  FROM PAR_90 GROUP BY ZONE_NME')
PAR180=sqldf('SELECT ZONE_NME,COUNT(DISTINCT ACCT_NBR) AS PAR_180_ACCT,SUM(LGR_BAL) AS PAR_180_OUTSTANDING  FROM PAR_180 GROUP BY ZONE_NME')


ZONE=sqldf('SELECT ZONE_NME FROM DISB  GROUP BY ZONE_NME')

A=merge(ZONE,PAR30,by="ZONE_NME",all.x = TRUE)
B=merge(A,PAR60,by="ZONE_NME",all.x = TRUE)
C=merge(B,PAR90,by="ZONE_NME",all.x = TRUE)
D=merge(C,PAR180,by="ZONE_NME",all.x = TRUE)

write.csv(D,"PAR_SUMMARY.CSV")






